# Generated by Django 3.2 on 2021-06-10 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food_category', '0002_auto_20210531_0326'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFacor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(max_length=100)),
                ('english_name', models.CharField(max_length=100)),
                ('number', models.IntegerField(blank=True)),
                ('classification', models.CharField(max_length=100)),
                ('collectionChannel', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('cns', models.CharField(max_length=100)),
                ('ins', models.CharField(max_length=100)),
                ('cas', models.CharField(max_length=100)),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('food_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_category', to='food_category.thirdcategory')),
            ],
            options={
                'verbose_name': '风险因子',
                'verbose_name_plural': '风险因子',
                'managed': True,
            },
        ),
    ]
