# Generated by Django 3.2 on 2021-06-10 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_factor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testfacor',
            old_name='collectionChannel',
            new_name='collectingChannel',
        ),
    ]
