# Generated by Django 3.2 on 2021-06-10 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_factor', '0002_rename_collectionchannel_testfacor_collectingchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testfacor',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
