# Generated by Django 3.2 on 2021-06-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_category', '0002_auto_20210531_0326'),
        ('test_factor', '0003_alter_testfacor_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestFacor',
            new_name='TestFactor',
        ),
    ]
