# Generated by Django 3.2 on 2021-05-19 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecondCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '食品亚类',
                'verbose_name_plural': '食品亚类',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '食品大类',
                'verbose_name_plural': '食品大类',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ThirdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='third_category', to='food_category.secondcategory')),
            ],
            options={
                'verbose_name': '食品次亚类',
                'verbose_name_plural': '食品次亚类',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='secondcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_category', to='food_category.topcategory'),
        ),
        migrations.CreateModel(
            name='FourthCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fourth_category', to='food_category.thirdcategory')),
            ],
            options={
                'verbose_name': '食品细类',
                'verbose_name_plural': '食品细类',
                'managed': True,
            },
        ),
    ]
