# Generated by Django 3.2 on 2021-05-31 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fourthcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='food_category.thirdcategory'),
        ),
        migrations.AlterField(
            model_name='secondcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='food_category.topcategory'),
        ),
        migrations.AlterField(
            model_name='thirdcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='food_category.secondcategory'),
        ),
    ]
